### ISSUE TITLE
knowage with Docker Menu disabled

### ISSUE THREAD

**Issue by MakremHammali** [KnowageLabs/Knowage-Server-Docker#27]
after runnig knowage in docker i can't get the menu  where data provider and profile management .. 
any help please 
![Annotation 2019-11-26 092538](https://user-images.githubusercontent.com/48314380/69611729-ba65df80-102e-11ea-87a4-c9d0b91a1530.png)

**Comment by Ape-Decendent** [comment]
Hello, I have deployed also in docker swarm and server settings are not visible and further configuration cannot be done. Appreciate some help here. 
<img width="1857" alt="image" src="https://user-images.githubusercontent.com/59166134/78584430-e006bf00-7840-11ea-9323-80c43f2c5ad9.png">

**Comment by kerny3d** [comment]
Dear all,

which version of Knowage do you deploy? Could you attach to this issue your Docker log? Which user have you used to login on Knowage?

**Comment by Ape-Decendent** [comment]
@kerny3d we followed the instructions from https://github.com/KnowageLabs/Knowage-Server-Docker and below is the docker file we have. We are running in Swarm.

version: "3.5"
  
services:
  knowage:
    image: knowagelabs/knowage-server-docker:7.1
    depends_on:
      - knowagedb
    ports:
      - "8082:8080"
    environment:
      - DB_USER=iudx
      - DB_PASS=iudx
      - DB_DB=iudx
      - DB_HOST=knowagedb
      - DB_PORT=3306
      - HMAC_KEY=iudx
      - PUBLIC_ADDRESS=localhost
    networks:
      front:
        aliases:
          - knowage.docker
      knowage:
      mongo:
      orion:
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  knowagedb:
    image: mysql:5.7
    environment:
      - MYSQL_USER=iudx
      - MYSQL_PASSWORD=iudx
      - MYSQL_DATABASE=iudx
      - MYSQL_ROOT_PASSWORD=iudx
    networks:
      - knowage
    volumes:
      - /opt/knowage-mysql:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: any


################################################################################
# Networks
################################################################################
networks:

    knowage:
        driver: overlay
        ipam:
            config:
                - subnet: 172.60.0.0/16
    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16
    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16
    orion:
        driver: overlay
        ipam:
            config:
                - subnet: 172.41.0.0/16

**Comment by kerny3d** [comment]
Dear @Ape-Decendent,

i've tried your YAML file on my local machine on Docker version 19.03.5, build 633a0ea838 and it works correctly.

Could you please get the logs from both MySql and Tomcat and upload them here?

Marco

**Comment by Ape-Decendent** [comment]
@kerny3d We are running this in Docker Swarm. I will try to pull some logs. I greatly appreciate your help.

**Comment by Ape-Decendent** [comment]
@Ape-Decendent @davide-zerbetto attaching the logs
[knowage_docker_logs.txt](https://github.com/KnowageLabs/Knowage-Server-Docker/files/4445276/knowage_docker_logs.txt)
[knowage_mysql_docker_logs.txt](https://github.com/KnowageLabs/Knowage-Server-Docker/files/4445278/knowage_mysql_docker_logs.txt)

**Comment by kerny3d** [comment]
@Ape-Decendent, quick question: which protocol are you using? HTTP or HTTPS?

**Comment by Ape-Decendent** [comment]
@kerny3d http

**Comment by kerny3d** [comment]
@Ape-Decendent, we are not able to replicate your case. On both docker-compose and swarm i see for biadmin:
![image](https://user-images.githubusercontent.com/6751879/78766309-675f4a00-7989-11ea-9422-7224b3fe5f03.png)
And for biuser:
![image](https://user-images.githubusercontent.com/6751879/78766456-91b10780-7989-11ea-8f51-8a71ba232955.png)
Could i ask you to start Knowage with the following docker-compose YAML file?
```
version: "3.5"

services:
  knowage:
    image: knowagelabs/knowage-server-docker:7.1
    depends_on:
      - knowagedb
    ports:
      - "8080:8080"
    volumes:
      - "./log4j.properties:/home/knowage/apache-tomcat-8.5.37/webapps/knowage/WEB-INF/classes/log4j.properties"
    environment:
      - DB_USER=iudx
      - DB_PASS=iudx
      - DB_DB=iudx
      - DB_HOST=knowagedb
      - DB_PORT=3306
      - HMAC_KEY=iudx
      - PUBLIC_ADDRESS=localhost
    networks:
      knowage:

  knowagedb:
    image: mysql:5.7
    environment:
      - MYSQL_USER=iudx
      - MYSQL_PASSWORD=iudx
      - MYSQL_DATABASE=iudx
      - MYSQL_ROOT_PASSWORD=iudx
    networks:
      - knowage
    volumes:
      - /opt/knowage-mysql:/var/lib/mysql

networks:
  knowage:
      driver: overlay
      ipam:
          config:
              - subnet: 172.60.0.0/16
```
Where the file log4j.properties is:
```
log4j.rootLogger=ERROR, CONSOLE

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Target=System.out
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.conversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p - %m%n

# Logger...
log4j.logger.Spago=ERROR,CONSOLE
log4j.additivity.Spago=false

log4j.logger.it.eng=ERROR,CONSOLE
log4j.additivity.it.eng=false

log4j.logger.it.eng.spagobi.commons.utilities.messages=ERROR, CONSOLE
log4j.logger.it.eng.spagobi.commons.utilities.urls.WebUrlBuilder=ERROR, CONSOLE

log4j.logger.org.quartz=ERROR, CONSOLE
log4j.logger.org.hibernate=ERROR, CONSOLE
log4j.logger.org.jbpm=ERROR, CONSOLE
log4j.logger.com.hazelcast=ERROR, CONSOLE

log4j.logger.audit=INFO, CONSOLE
log4j.additivity.audit=false

log4j.logger.dataset.audit=ERROR, CONSOLE
log4j.additivity.dataset.audit=false

log4j.logger.it.eng.spagobi.tools.dataset.common.dataproxy.JDBCDataProxy=INFO, CONSOLE
log4j.additivity.it.eng.spagobi.tools.dataset.common.dataproxy.JDBCDataProxy=false
log4j.logger.it.eng.spagobi.tools.dataset.common.dataproxy.JDBCRedShiftDataProxy=INFO, CONSOLE
log4j.additivity.it.eng.spagobi.tools.dataset.common.dataproxy.JDBCRedShiftDataProxy=false

log4j.logger.it.eng.knowage.tools.servermanager=ERROR, CONSOLE
log4j.additivity.it.eng=false
```
Could you replicate your case again and extract the logs from your environment? We hope we can find the problem this time.
