### ISSUE TITLE
knowage 7.3 with docker do not start

### ISSUE THREAD

**Issue by JoanoToxo** [KnowageLabs/Knowage-Server-Docker#38]
Hi
I just installed knowage with docker:

$ docker-compose up -d
WARNING: The HMAC_KEY variable is not set. Defaulting to a blank string.
WARNING: The PASSWORD_ENCRYPTION_SECRET variable is not set. Defaulting to a blank string.
Starting knowage-server-docker_knowager_1      ... done
Starting knowage-server-docker_knowagepython_1 ... done
Starting knowage-server-docker_knowagedb_1     ... done
Starting knowage-server-docker_knowage_1       ... done

But only the mariadb container remains:

$ docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS         PORTS      NAMES
f2a0f7e1ff04   mariadb:10.3   "docker-entrypoint.s…"   20 minutes ago   Up 9 minutes   3306/tcp   knowage-server-docker_knowagedb_1

The other 3 containers do not start:

$ docker ps -a
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                        PORTS      NAMES
1e266537d5cd   knowagelabs/knowage-server-docker:7.3.0-SNAPSHOT   "./entrypoint.sh ./a…"   21 minutes ago   Exited (255) 10 minutes ago              1e266537d5cd_knowage-server-docker_knowage_1
16d6b602287c   knowagelabs/knowage-python-docker:7.2              "./entrypoint.sh gun…"   21 minutes ago   Exited (255) 10 minutes ago              knowage-server-docker_knowagepython_1
f2a0f7e1ff04   mariadb:10.3                                       "docker-entrypoint.s…"   21 minutes ago   Up 10 minutes                 3306/tcp   knowage-server-docker_knowagedb_1
f12a11c22d68   knowagelabs/knowage-r-docker:7.2                   "./entrypoint.sh r k…"   21 minutes ago   Exited (255) 10 minutes ago              knowage-server-docker_knowager_1

I have not modified any settings.
Which may be due?

Regards

**Comment by Redjaw** [comment]
Hi,
the two warnings seems not to be related to 7.3 version.
Can you try to pull from docker the snapshot?
`docker pull knowagelabs/knowage-server-docker:7.3.0-SNAPSHOT`

Maybe it's just a cache issue.

**Comment by JoanoToxo** [comment]
Hi, the same thing happened

$ docker ps -a
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                        PORTS      NAMES
267a4e0d2991   knowagelabs/knowage-server-docker:7.3.0-SNAPSHOT   "./entrypoint.sh ./a…"   29 seconds ago   Exited (255) 18 seconds ago              knowage-server-docker_knowage_1
12413eefcd24   knowagelabs/knowage-python-docker:7.2              "./entrypoint.sh gun…"   30 seconds ago   Exited (255) 29 seconds ago              knowage-server-docker_knowagepython_1
02a40dc0d796   mariadb:10.3                                       "docker-entrypoint.s…"   30 seconds ago   Up 29 seconds                 3306/tcp   knowage-server-docker_knowagedb_1
47daa1c82526   knowagelabs/knowage-r-docker:7.2                   "./entrypoint.sh r k…"   30 seconds ago   Exited (255) 29 seconds ago              knowage-server-docker_knowager_1

**Comment by kerny3d** [comment]
@JoanoToxo,

you need to set HMAC_KEY and PASSWORD_ENCRYPTION_SECRET environment variables: see https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/Knowage-Server-Docker/README.md

If you look at the log you should see the error on init.

**Comment by JoanoToxo** [comment]
it do not work.

$ cat .env
DB_USER=knowageuser
DB_DB=knowagedb
DB_PASS=knowagepassword
DB_HOST=knowagedb
DB_PORT=3306
DB_ROOT_PASS=knowagepassword

$ docker-compose up -d
WARNING: The HMAC_KEY variable is not set. Defaulting to a blank string.
WARNING: The PASSWORD_ENCRYPTION_SECRET variable is not set. Defaulting to a blank string.
Creating network "knowage-server-docker_main" with the default driver
Creating knowage-server-docker_knowagedb_1     ... done
Creating knowage-server-docker_knowager_1      ... done
Creating knowage-server-docker_knowagepython_1 ... done
Creating knowage-server-docker_knowage_1       ... done

$ docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS      NAMES
359320a94bf3   mariadb:10.3   "docker-entrypoint.s…"   15 seconds ago   Up 14 seconds   3306/tcp   knowage-server-docker_knowagedb_1

$ docker ps -a
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                        PORTS      NAMES
1b65dcd7ecef   knowagelabs/knowage-server-docker:7.3.0-SNAPSHOT   "./entrypoint.sh ./a…"   25 seconds ago   Exited (255) 24 seconds ago              knowage-server-docker_knowage_1
0da5435f88a0   knowagelabs/knowage-python-docker:7.2              "./entrypoint.sh gun…"   26 seconds ago   Exited (255) 25 seconds ago              knowage-server-docker_knowagepython_1
359320a94bf3   mariadb:10.3                                       "docker-entrypoint.s…"   26 seconds ago   Up 25 seconds                 3306/tcp   knowage-server-docker_knowagedb_1
722dc514eeac   knowagelabs/knowage-r-docker:7.2                   "./entrypoint.sh r k…"   26 seconds ago   Exited (255) 25 seconds ago              knowage-server-docker_knowager_1

$ cat .env
DB_USER=knowageuser
DB_DB=knowagedb
DB_PASS=knowagepassword
DB_HOST=knowagedb
DB_PORT=3306
DB_ROOT_PASS=knowagepassword
HMAC_KEY=1234567890
PASSWORD_ENCRYPTION_SECRET=1234567890

$ docker-compose up -d
knowage-server-docker_knowagedb_1 is up-to-date
Recreating knowage-server-docker_knowager_1 ... 
Recreating knowage-server-docker_knowagepython_1 ... 
Recreating knowage-server-docker_knowage_1       ... error

ERROR: for knowage-server-docker_knowage_1  Cannot create container for service knowage: invalid volume specificaRecreating knowage-server-docker_knowager_1      ... doneRecreating knowage-server-docker_knowagepython_1 ... doneath must be absolute

ERROR: for knowage  Cannot create container for service knowage: invalid volume specification: '98caf7a96a07421ae5218176ed90f4dc53fc4e4ec87f080fe408c3502a03348d:[/home/knowage/apache-tomcat/resources]:rw': invalid mount config for type "volume": invalid mount path: '[/home/knowage/apache-tomcat/resources]' mount path must be absolute
ERROR: Encountered errors while bringing up the project.

**Comment by kerny3d** [comment]
Hi @JoanoToxo,

sorry about that: it was a bug. I've pushed the fixed image:

https://hub.docker.com/layers/knowagelabs/knowage-server-docker/7.3.0-SNAPSHOT/images/sha256-6e7698e14111469098e83fbf1444d8259adc35d7822f86d242a8cc3dcdbeb23c?context=explore

Thank you for your issue.

**Comment by JoanoToxo** [comment]
Hi, I just tried it but it doesn't work

**Comment by kerny3d** [comment]
Hi,

with the last image:

`knowagelabs/knowage-server-docker   7.3.0-SNAPSHOT      **4e01411bcc62**        6 days ago          2.31GB`

It seems to work just fine with the following docker-compose:

```
version: "3.1"
services:
  knowage:
    image: knowagelabs/knowage-server-docker:7.3.0-SNAPSHOT
    depends_on:
      - knowagedb
      - knowagepython
      - knowager
    ports:
      - "8081:8080"
    networks:
      - main
    environment:
      - DB_USER=knowage
      - DB_PASS=knowage
      - DB_DB=knowage
      - DB_HOST=knowagedb
      - DB_PORT=3306
      - HMAC_KEY=abc123
      - PASSWORD_ENCRYPTION_SECRET=def456
      - PUBLIC_ADDRESS=localhost
    volumes:
      - ./resource:/home/knowage/apache-tomcat/resources

  knowagepython:
    image: knowagelabs/knowage-python-docker:7.3.0-SNAPSHOT
    environment:
      - HMAC_KEY=abc123
      - KNOWAGE_PUBLIC_ADDRESS=knowage
      - PUBLIC_ADDRESS=localhost
    networks:
      - main

  knowager:
    image: knowagelabs/knowage-r-docker:7.3.0-SNAPSHOT
    environment:
      - HMAC_KEY=abc123
    networks:
      - main

  knowagedb:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=knowage
      - MYSQL_PASSWORD=knowage
      - MYSQL_DATABASE=knowage
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - main
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db:

networks:
  main:
```

What's your log?
