### ISSUE TITLE
create cockpit result in a path error

### ISSUE THREAD

**Issue by zabuTNT** [KnowageLabs/Knowage-Server-Docker#5]
I'm using the 6.1.1 image:

> knowagelabs/knowage-server-docker:6.1.1 

and I was following this document:
https://knowage.readthedocs.io/en/latest/user/NGSI/README/index.html#document-definition

I successfull added a Dataset REST with Orion Context Broker but when I try to create a Cockpit with an user in Analysis section I ran into an error caused by a resource not found..
The browser downloads a file named: 

> ndefined&SBI_ENVIRONMENT=WORKSPACE&IS_TECHNICAL_USER=false&documentMode=EDIT 

containing this:

`{"service":"","errors":[{"message":"RESTEASY003210: Could not find resource for full path: http://<MYIP>:<MYPORT>/knowage/restful-services/undefined&SBI_ENVIRONMENT=WORKSPACE&IS_TECHNICAL_USER=false&documentMode=EDIT"}]}`

I don't know if it related to only docker version or a general Knowage-Server. What is that undefined variable? I miss something in the configuration?

**Comment by aportosa** [comment]
You have to use the **Docker Compose file** to instantiate Knowage properly.
Please have a look at the documentation.

The image itself is not enough to have a working instance of Knowage.

**Comment by zabuTNT** [comment]
I run it with docker-compose, I only change the external port from 8080 to 4001.

```knowage:
    image: knowagelabs/knowage-server-docker:6.1.1
    links:
        - knowagedb:db
    ports:
        - "4001:8080"
    environment:
        - WAIT_MYSQL=true

knowagedb:
    image: mysql:5.5
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
```

**Comment by aportosa** [comment]
I guess this is because you didn't set the PUBLIC_ADDRESS under environment in you custom docker-compose.yml: https://github.com/KnowageLabs/Knowage-Server-Docker#properties

```
    image: knowagelabs/knowage-server-docker:6.1.1
    links:
        - knowagedb:db
    ports:
        - "4001:8080"
    environment:
        - WAIT_MYSQL=true
        - PUBLIC_ADDRESS=<you_ip>

knowagedb:
    image: mysql:5.5
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
```

Please try with this
