### ISSUE TITLE
knowagej 7.4.x  start error?

### ISSUE THREAD

**Issue by zengxc-1996** [KnowageLabs/Knowage-Server-Docker#50]
centos 7.x: 

![image](https://user-images.githubusercontent.com/63622990/123914452-fe128f00-d9b1-11eb-8221-8792f096e2ff.png)

I tried to use all versions of 7.4.x with this error.

I ran it in the compose file.

Now I think there's something wrong with the mirror image.

I don't know how to deal with it. I am looking forward to your help. Thank you very much.

**Comment by zengxc-1996** [comment]
docker-compose up  -d

start error:

```
ERROR: for knowage  Cannot start service knowage: OCI runtime create failed: invalid mount {Destination:[/home/knowage/apache-tomcat/resources] Type:bind Source:/var/lib/docker/volumes/6c3677804e0662777041a3354d3d260d4a29a2abf8811af788bcd1e6b6d8d821/_data Options:[rbind]}: mount destination [/home/knowage/apache-tomcat/resources] not absolute: unknown
ERROR: Encountered errors while bringing up the project.
```

![image](https://user-images.githubusercontent.com/63622990/123888463-2389a380-d986-11eb-8c0f-3c813345ab77.png)

**Comment by kerny3d** [comment]
Hi, could you please attach to this issue the original YAML file? In particular, we need to check the volumes section of the main container.

Trying with:
```
version: "3.1"
services:
  knowage:
    image: knowagelabs/knowage-server-docker:8.0.0-SNAPSHOT
    depends_on:
      - knowagedb
      - knowagecache
      - hazelcast
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DB=$DB_DB
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS

      - CACHE_DB_HOST=$CACHE_DB_HOST
      - CACHE_DB_PORT=$CACHE_DB_PORT
      - CACHE_DB_DB=$CACHE_DB_DB
      - CACHE_DB_USER=$CACHE_DB_USER
      - CACHE_DB_PASS=$CACHE_DB_PASS

      - HMAC_KEY=$HMAC_KEY
      - PASSWORD_ENCRYPTION_SECRET=$PASSWORD_ENCRYPTION_SECRET
      - PUBLIC_ADDRESS=localhost

      - HAZELCAST_HOSTS=hazelcast
      - HAZELCAST_PORT=5701
    volumes:
      - ./resources:/home/knowage/apache-tomcat/resources
```
Seems to work just fine.
